import { Type } from '@/types/Type';
import { IconName } from '@fortawesome/fontawesome-svg-core';

export const typeIcons: { [key in Type]: IconName } = {
	normal: 'certificate',
	fighting: 'hand-back-fist',
	flying: 'feather',
	grass: 'leaf',
	water: 'droplet',
	fire: 'fire',
	electric: 'bolt',
	ice: 'snowflake',
	ground: 'explosion',
	rock: 'mountain',
	poison: 'flask',
	bug: 'bug',
	fairy: 'wand-sparkles',
	dark: 'moon',
	psychic: 'podcast',
	ghost: 'ghost',
	dragon: 'dragon',
	steel: 'gear',
};

export const typeColors: { [key in Type]: string } = {
	normal: 'stone-400',
	fighting: 'amber-700',
	flying: 'sky-600',
	grass: 'green-700',
	water: 'blue-700',
	fire: 'red-700',
	electric: 'yellow-500',
	ice: 'cyan-300',
	ground: 'yellow-700',
	rock: 'amber-900',
	poison: 'fushia-800',
	bug: 'lime-300',
	fairy: 'yellow-200',
	dark: 'violet-900',
	psychic: 'purple-800',
	ghost: 'indigo-900',
	dragon: 'indigo-700',
	steel: 'slate-500',
};

export const typeBrightness: { [key in Type]: 'light' | 'dark' } = {
	normal: 'light',
	fighting: 'dark',
	flying: 'light',
	grass: 'dark',
	water: 'dark',
	fire: 'dark',
	electric: 'light',
	ice: 'light',
	ground: 'dark',
	rock: 'dark',
	poison: 'dark',
	bug: 'light',
	fairy: 'light',
	dark: 'dark',
	psychic: 'dark',
	ghost: 'dark',
	dragon: 'dark',
	steel: 'light',
};
