import { Type } from '@/types/Type';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
	faBolt,
	faStar,
	faHandFist,
	faFeather,
	faLeaf,
	faDroplet,
	faFire,
	faSnowflake,
	faFlask,
	faMountain,
	faBug,
	faWandSparkles,
	faMoon,
	faPodcast,
	faGhost,
	faDragon,
	faExplosion,
	faShield,
} from '@fortawesome/free-solid-svg-icons';

export const typeIcons: { [key in Type]: IconDefinition } = {
	Normal: faStar,
	Fighting: faHandFist,
	Flying: faFeather,
	Grass: faLeaf,
	Water: faDroplet,
	Fire: faFire,
	Electric: faBolt,
	Ice: faSnowflake,
	Ground: faExplosion,
	Rock: faMountain,
	Poison: faFlask,
	Bug: faBug,
	Fairy: faWandSparkles,
	Dark: faMoon,
	Psychic: faPodcast,
	Ghost: faGhost,
	Dragon: faDragon,
	Steel: faShield,
};

export const typeColors: { [key in Type]: string } = {
	Normal: 'stone-400',
	Fighting: 'amber-700',
	Flying: 'sky-400',
	Grass: 'green-700',
	Water: 'blue-700',
	Fire: 'red-700',
	Electric: 'yellow-500',
	Ice: 'cyan-300',
	Ground: 'yellow-700',
	Rock: 'amber-900',
	Poison: 'fuchsia-800',
	Bug: 'lime-600',
	Fairy: 'pink-400',
	Dark: 'violet-900',
	Psychic: 'purple-800',
	Ghost: 'indigo-900',
	Dragon: 'indigo-700',
	Steel: 'slate-500',
};

export const typeBrightness: { [key in Type]: 'light' | 'dark' } = {
	Normal: 'light',
	Fighting: 'dark',
	Flying: 'light',
	Grass: 'dark',
	Water: 'dark',
	Fire: 'dark',
	Electric: 'light',
	Ice: 'light',
	Ground: 'dark',
	Rock: 'dark',
	Poison: 'dark',
	Bug: 'light',
	Fairy: 'light',
	Dark: 'dark',
	Psychic: 'dark',
	Ghost: 'dark',
	Dragon: 'dark',
	Steel: 'light',
};
